package xyz.wadewhy.after.sys.mapper;

import org.apache.ibatis.annotations.Param;
import xyz.wadewhy.after.sys.domain.Role;

import java.util.List;
import java.util.Map;

public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated
     */
    int insertSelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated
     */
    Role selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Role record);

    /**
     * 根据用户id查询拥有的角色ID
     * @param uid
     * @return
     */
    List<Integer> queryRoleIdsByUserId(Integer uid);

    /**
     * 根据角色ID查询当前角色拥有的所有的权限或菜单ID
     * @param rid
     * @return
     */
    List<Integer> queryRolePermissionIdsByRid(Integer rid);

    /**
     * 删除role_permission记录
     * @param pid
     * @return
     */
    int deleteByPid(Integer pid);

    List<Role> findList(Map<String, Object> queryMap);

    int getTotal(Map<String, Object> queryMap);


    List<Role> findRoleByUid(@Param("ids") List<Integer> ids);

    List<Role> findAllRole();


}