package xyz.wadewhy.after.bus.mapper;

import xyz.wadewhy.after.bus.domain.ExamPaperCreate;

import java.util.List;

public interface ExamPaperCreateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_exampapercreate
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_exampapercreate
     *
     * @mbg.generated
     */
    int insert(ExamPaperCreate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_exampapercreate
     *
     * @mbg.generated
     */
    int insertSelective(ExamPaperCreate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_exampapercreate
     *
     * @mbg.generated
     */
    ExamPaperCreate selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_exampapercreate
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ExamPaperCreate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_exampapercreate
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ExamPaperCreate record);

    List<ExamPaperCreate> findByExamId(Integer examId);
}