package xyz.wadewhy.after.bus.mapper;

import xyz.wadewhy.after.bus.domain.ExamPaper;

import java.util.List;
import java.util.Map;

public interface ExamPaperMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_exampaper
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_exampaper
     *
     * @mbg.generated
     */
    int insert(ExamPaper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_exampaper
     *
     * @mbg.generated
     */
    int insertSelective(ExamPaper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_exampaper
     *
     * @mbg.generated
     */
    ExamPaper selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_exampaper
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ExamPaper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_exampaper
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ExamPaper record);

    ExamPaper find(Map<String, Object> queryMap);

    int submitPaper(ExamPaper examPaper);

    List<ExamPaper> findHistory(Map<String, Object> queryMap);

    List<ExamPaper> findList(Map<String, Object> queryMap);

    int getTotal(Map<String, Object> queryMap);

    List<Map<String, Object>> getExamStats(Integer examId);
}