package xyz.wadewhy.after.bus.mapper;

import org.apache.ibatis.annotations.Param;
import xyz.wadewhy.after.bus.domain.Question_Option;

import java.util.List;

public interface Question_OptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_question_option
     *
     * @mbg.generated
     */
    int insert(Question_Option record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_question_option
     *
     * @mbg.generated
     */
    int insertSelective(Question_Option record);

    List<Question_Option> findQuestionAndOptionById(@Param("qid") Integer questionId);

    int UpdateQuestion_Option(Question_Option question_option);
}