package xyz.wadewhy.after.bus.mapper;

import xyz.wadewhy.after.bus.domain.Question;

import java.util.List;
import java.util.Map;

public interface QuestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_question
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_question
     *
     * @mbg.generated
     */
    int insert(Question record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_question
     *
     * @mbg.generated
     */
    int insertSelective(Question record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_question
     *
     * @mbg.generated
     */
    Question selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_question
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Question record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_question
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(Question record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_question
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Question record);

    int insertQuestionAndGetId(Question question);

    List<Question> findList(Map<String, Object> queryMap);

    int getTotal(Map<String, Object> queryMap);

    int getQuestionNumByType(Map<String, Integer> queryMap);
}