package xyz.wadewhy.after.bus.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import xyz.wadewhy.after.bus.domain.Student;
import xyz.wadewhy.after.bus.domain.studentExample;

public interface StudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_student
     *
     * @mbg.generated
     */
    long countByExample(studentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_student
     *
     * @mbg.generated
     */
    int deleteByExample(studentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_student
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_student
     *
     * @mbg.generated
     */
    int insert(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_student
     *
     * @mbg.generated
     */
    int insertSelective(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_student
     *
     * @mbg.generated
     */
    List<Student> selectByExample(studentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_student
     *
     * @mbg.generated
     */
    Student selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_student
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Student record, @Param("example") studentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_student
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Student record, @Param("example") studentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_student
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_student
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Student record);

    List<Student> findList(Map<String, Object> queryMap);

    int getTotal(Map<String, Object> queryMap);

    Student findByName(@Param("name") String name, @Param("id") Long id);
}