package xyz.wadewhy.after.bus.domain;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

public class Exam {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_exam.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_exam.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_exam.subjectId
     *
     * @mbg.generated
     */
    private Integer subjectid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_exam.startTime
     *
     * @mbg.generated
     */
    private Date starttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_exam.endTime
     *
     * @mbg.generated
     */
    private Date endtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_exam.avaliableTime
     *
     * @mbg.generated
     */
    private Integer avaliabletime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_exam.questionNum
     *
     * @mbg.generated
     */
    private Integer questionnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_exam.totalScore
     *
     * @mbg.generated
     */
    private Integer totalscore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_exam.passScore
     *
     * @mbg.generated
     */
    private Integer passscore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_exam.singleQuestionNum
     *
     * @mbg.generated
     */
    private Integer singlequestionnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_exam.muiltQuestionNum
     *
     * @mbg.generated
     */
    private Integer muiltquestionnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_exam.writeQuestionNum
     *
     * @mbg.generated
     */
    private Integer writequestionnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_exam.chargeQuestionNum
     *
     * @mbg.generated
     */
    private Integer chargequestionnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_exam.paperNum
     *
     * @mbg.generated
     */
    private Integer papernum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_exam.bus_examedNum
     *
     * @mbg.generated
     */
    private Integer examedNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_exam.passNum
     *
     * @mbg.generated
     */
    private Integer passnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_exam.createTime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_exam.id
     *
     * @return the value of bus_exam.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_exam.id
     *
     * @param id the value for bus_exam.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_exam.name
     *
     * @return the value of bus_exam.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_exam.name
     *
     * @param name the value for bus_exam.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_exam.subjectId
     *
     * @return the value of bus_exam.subjectId
     *
     * @mbg.generated
     */
    public Integer getSubjectid() {
        return subjectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_exam.subjectId
     *
     * @param subjectid the value for bus_exam.subjectId
     *
     * @mbg.generated
     */
    public void setSubjectid(Integer subjectid) {
        this.subjectid = subjectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_exam.startTime
     *
     * @return the value of bus_exam.startTime
     *
     * @mbg.generated
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_exam.startTime
     *
     * @param starttime the value for bus_exam.startTime
     *
     * @mbg.generated
     */
    public void setStarttime(String starttime) {
        System.err.println("【starttime】");
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        try {
            System.err.println(sdf.parse(starttime));
            this.starttime = sdf.parse(starttime);
        } catch (ParseException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_exam.endTime
     *
     * @return the value of bus_exam.endTime
     *
     * @mbg.generated
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_exam.endTime
     *
     * @param endtime the value for bus_exam.endTime
     *
     * @mbg.generated
     */
    public void setEndtime(String endtime) {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        try {
            this.endtime = sdf.parse(endtime);
        } catch (ParseException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_exam.avaliableTime
     *
     * @return the value of bus_exam.avaliableTime
     *
     * @mbg.generated
     */
    public Integer getAvaliabletime() {
        return avaliabletime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_exam.avaliableTime
     *
     * @param avaliabletime the value for bus_exam.avaliableTime
     *
     * @mbg.generated
     */
    public void setAvaliabletime(Integer avaliabletime) {
        this.avaliabletime = avaliabletime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_exam.questionNum
     *
     * @return the value of bus_exam.questionNum
     *
     * @mbg.generated
     */
    public Integer getQuestionnum() {
        return questionnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_exam.questionNum
     *
     * @param questionnum the value for bus_exam.questionNum
     *
     * @mbg.generated
     */
    public void setQuestionnum(Integer questionnum) {
        this.questionnum = questionnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_exam.totalScore
     *
     * @return the value of bus_exam.totalScore
     *
     * @mbg.generated
     */
    public Integer getTotalscore() {
        return totalscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_exam.totalScore
     *
     * @param totalscore the value for bus_exam.totalScore
     *
     * @mbg.generated
     */
    public void setTotalscore(Integer totalscore) {
        this.totalscore = totalscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_exam.passScore
     *
     * @return the value of bus_exam.passScore
     *
     * @mbg.generated
     */
    public Integer getPassscore() {
        return passscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_exam.passScore
     *
     * @param passscore the value for bus_exam.passScore
     *
     * @mbg.generated
     */
    public void setPassscore(Integer passscore) {
        this.passscore = passscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_exam.singleQuestionNum
     *
     * @return the value of bus_exam.singleQuestionNum
     *
     * @mbg.generated
     */
    public Integer getSinglequestionnum() {
        return singlequestionnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_exam.singleQuestionNum
     *
     * @param singlequestionnum the value for bus_exam.singleQuestionNum
     *
     * @mbg.generated
     */
    public void setSinglequestionnum(Integer singlequestionnum) {
        this.singlequestionnum = singlequestionnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_exam.muiltQuestionNum
     *
     * @return the value of bus_exam.muiltQuestionNum
     *
     * @mbg.generated
     */
    public Integer getMuiltquestionnum() {
        return muiltquestionnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_exam.muiltQuestionNum
     *
     * @param muiltquestionnum the value for bus_exam.muiltQuestionNum
     *
     * @mbg.generated
     */
    public void setMuiltquestionnum(Integer muiltquestionnum) {
        this.muiltquestionnum = muiltquestionnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_exam.writeQuestionNum
     *
     * @return the value of bus_exam.writeQuestionNum
     *
     * @mbg.generated
     */
    public Integer getWritequestionnum() {
        return writequestionnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_exam.writeQuestionNum
     *
     * @param writequestionnum the value for bus_exam.writeQuestionNum
     *
     * @mbg.generated
     */
    public void setWritequestionnum(Integer writequestionnum) {
        this.writequestionnum = writequestionnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_exam.chargeQuestionNum
     *
     * @return the value of bus_exam.chargeQuestionNum
     *
     * @mbg.generated
     */
    public Integer getChargequestionnum() {
        return chargequestionnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_exam.chargeQuestionNum
     *
     * @param chargequestionnum the value for bus_exam.chargeQuestionNum
     *
     * @mbg.generated
     */
    public void setChargequestionnum(Integer chargequestionnum) {
        this.chargequestionnum = chargequestionnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_exam.paperNum
     *
     * @return the value of bus_exam.paperNum
     *
     * @mbg.generated
     */
    public Integer getPapernum() {
        return papernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_exam.paperNum
     *
     * @param papernum the value for bus_exam.paperNum
     *
     * @mbg.generated
     */
    public void setPapernum(Integer papernum) {
        this.papernum = papernum;
    }

    public Integer getExamedNum() {
        return examedNum;
    }

    public void setExamedNum(Integer examedNum) {
        this.examedNum = examedNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_exam.passNum
     *
     * @return the value of bus_exam.passNum
     *
     * @mbg.generated
     */
    public Integer getPassnum() {
        return passnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_exam.passNum
     *
     * @param passnum the value for bus_exam.passNum
     *
     * @mbg.generated
     */
    public void setPassnum(Integer passnum) {
        this.passnum = passnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_exam.createTime
     *
     * @return the value of bus_exam.createTime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_exam.createTime
     *
     * @param createtime the value for bus_exam.createTime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    @Override
    public String toString() {
        return "Exam{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", subjectid=" + subjectid +
                ", starttime=" + starttime +
                ", endtime=" + endtime +
                ", avaliabletime=" + avaliabletime +
                ", questionnum=" + questionnum +
                ", totalscore=" + totalscore +
                ", passscore=" + passscore +
                ", singlequestionnum=" + singlequestionnum +
                ", muiltquestionnum=" + muiltquestionnum +
                ", writequestionnum=" + writequestionnum +
                ", chargequestionnum=" + chargequestionnum +
                ", papernum=" + papernum +
                ", examedNum=" + examedNum +
                ", passnum=" + passnum +
                ", createtime=" + createtime +
                '}';
    }
}