package xyz.wadewhy.after.bus.domain;

public class ExamPaperCreate {
    @Override
    public String toString() {
        return "ExamPaperCreate{" +
                "id=" + id +
                ", examid=" + examid +
                ", exampaperid=" + exampaperid +
                ", studentid=" + studentid +
                ", questionid=" + questionid +
                ", answer='" + answer + '\'' +
                '}';
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_exampapercreate.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_exampapercreate.examId
     *
     * @mbg.generated
     */
    private Integer examid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_exampapercreate.examPaperId
     *
     * @mbg.generated
     */
    private Integer exampaperid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_exampapercreate.studentId
     *
     * @mbg.generated
     */
    private Integer studentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_exampapercreate.questionId
     *
     * @mbg.generated
     */
    private Integer questionid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_exampapercreate.answer
     *
     * @mbg.generated
     */
    private String answer;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_exampapercreate.id
     *
     * @return the value of bus_exampapercreate.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_exampapercreate.id
     *
     * @param id the value for bus_exampapercreate.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_exampapercreate.examId
     *
     * @return the value of bus_exampapercreate.examId
     *
     * @mbg.generated
     */
    public Integer getExamid() {
        return examid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_exampapercreate.examId
     *
     * @param examid the value for bus_exampapercreate.examId
     *
     * @mbg.generated
     */
    public void setExamid(Integer examid) {
        this.examid = examid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_exampapercreate.examPaperId
     *
     * @return the value of bus_exampapercreate.examPaperId
     *
     * @mbg.generated
     */
    public Integer getExampaperid() {
        return exampaperid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_exampapercreate.examPaperId
     *
     * @param exampaperid the value for bus_exampapercreate.examPaperId
     *
     * @mbg.generated
     */
    public void setExampaperid(Integer exampaperid) {
        this.exampaperid = exampaperid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_exampapercreate.studentId
     *
     * @return the value of bus_exampapercreate.studentId
     *
     * @mbg.generated
     */
    public Integer getStudentid() {
        return studentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_exampapercreate.studentId
     *
     * @param studentid the value for bus_exampapercreate.studentId
     *
     * @mbg.generated
     */
    public void setStudentid(Integer studentid) {
        this.studentid = studentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_exampapercreate.questionId
     *
     * @return the value of bus_exampapercreate.questionId
     *
     * @mbg.generated
     */
    public Integer getQuestionid() {
        return questionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_exampapercreate.questionId
     *
     * @param questionid the value for bus_exampapercreate.questionId
     *
     * @mbg.generated
     */
    public void setQuestionid(Integer questionid) {
        this.questionid = questionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_exampapercreate.answer
     *
     * @return the value of bus_exampapercreate.answer
     *
     * @mbg.generated
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_exampapercreate.answer
     *
     * @param answer the value for bus_exampapercreate.answer
     *
     * @mbg.generated
     */
    public void setAnswer(String answer) {
        this.answer = answer == null ? null : answer.trim();
    }
}