package xyz.wadewhy.after.bus.domain;

public class Question_Option {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_question_option.qid
     *
     * @mbg.generated
     */
    private Integer qid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_question_option.selectoption
     *
     * @mbg.generated
     */
    private String selectoption;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_question_option.optionanswer
     *
     * @mbg.generated
     */
    private String optionanswer;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_question_option.qid
     *
     * @return the value of bus_question_option.qid
     *
     * @mbg.generated
     */
    public Integer getQid() {
        return qid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_question_option.qid
     *
     * @param qid the value for bus_question_option.qid
     *
     * @mbg.generated
     */
    public void setQid(Integer qid) {
        this.qid = qid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_question_option.selectoption
     *
     * @return the value of bus_question_option.selectoption
     *
     * @mbg.generated
     */
    public String getSelectoption() {
        return selectoption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_question_option.selectoption
     *
     * @param selectoption the value for bus_question_option.selectoption
     *
     * @mbg.generated
     */
    public void setSelectoption(String selectoption) {
        this.selectoption = selectoption == null ? null : selectoption.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_question_option.optionanswer
     *
     * @return the value of bus_question_option.optionanswer
     *
     * @mbg.generated
     */
    public String getOptionanswer() {
        return optionanswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_question_option.optionanswer
     *
     * @param optionanswer the value for bus_question_option.optionanswer
     *
     * @mbg.generated
     */
    public void setOptionanswer(String optionanswer) {
        this.optionanswer = optionanswer == null ? null : optionanswer.trim();
    }

    @Override
    public String toString() {
        return "Question_Option{" +
                "qid=" + qid +
                ", selectoption='" + selectoption + '\'' +
                ", optionanswer='" + optionanswer + '\'' +
                '}';
    }
}