package xyz.wadewhy.after.bus.domain;

import java.util.Date;

public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_student.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_student.subjectId
     *
     * @mbg.generated
     */
    private Integer subjectid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_student.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_student.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_student.trueName
     *
     * @mbg.generated
     */
    private String truename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_student.tel
     *
     * @mbg.generated
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_student.createTime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_student.salt
     *
     * @mbg.generated
     */
    private String salt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_student.id
     *
     * @return the value of bus_student.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_student.id
     *
     * @param id the value for bus_student.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_student.subjectId
     *
     * @return the value of bus_student.subjectId
     *
     * @mbg.generated
     */
    public Integer getSubjectid() {
        return subjectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_student.subjectId
     *
     * @param subjectid the value for bus_student.subjectId
     *
     * @mbg.generated
     */
    public void setSubjectid(Integer subjectid) {
        this.subjectid = subjectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_student.name
     *
     * @return the value of bus_student.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_student.name
     *
     * @param name the value for bus_student.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_student.password
     *
     * @return the value of bus_student.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_student.password
     *
     * @param password the value for bus_student.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_student.trueName
     *
     * @return the value of bus_student.trueName
     *
     * @mbg.generated
     */
    public String getTruename() {
        return truename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_student.trueName
     *
     * @param truename the value for bus_student.trueName
     *
     * @mbg.generated
     */
    public void setTruename(String truename) {
        this.truename = truename == null ? null : truename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_student.tel
     *
     * @return the value of bus_student.tel
     *
     * @mbg.generated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_student.tel
     *
     * @param tel the value for bus_student.tel
     *
     * @mbg.generated
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_student.createTime
     *
     * @return the value of bus_student.createTime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_student.createTime
     *
     * @param createtime the value for bus_student.createTime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_student.salt
     *
     * @return the value of bus_student.salt
     *
     * @mbg.generated
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_student.salt
     *
     * @param salt the value for bus_student.salt
     *
     * @mbg.generated
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    @Override
    public String toString() {
        return "Student{" +
                "id=" + id +
                ", subjectid=" + subjectid +
                ", name='" + name + '\'' +
                ", password='" + password + '\'' +
                ", truename='" + truename + '\'' +
                ", tel='" + tel + '\'' +
                ", createtime=" + createtime +
                ", salt='" + salt + '\'' +
                '}';
    }
}