package xyz.wadewhy.before.bus.mapper;

import xyz.wadewhy.before.domain.ExamPaperAnswer;

import java.util.List;
import java.util.Map;

public interface ExamPaperAnswerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_exampaperanswer
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_exampaperanswer
     *
     * @mbg.generated
     */
    int insert(ExamPaperAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_exampaperanswer
     *
     * @mbg.generated
     */
    int insertSelective(ExamPaperAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_exampaperanswer
     *
     * @mbg.generated
     */
    ExamPaperAnswer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_exampaperanswer
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ExamPaperAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_exampaperanswer
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ExamPaperAnswer record);

    List<ExamPaperAnswer> findListByUser(Map<String, Object> queryMap);

    int submitWriterAnswer(ExamPaperAnswer examPaperAnswer);

    List<ExamPaperAnswer> findList(Map<String, Object> queryMap);

    int getTotal(Map<String, Object> queryMap);

//    int submitAnswer(ExamPaperAnswer examPaperAnswer);
}